imageTag: armv7
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 180
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 180
minecraftServer:
  eula: true
  version: '1.15.2'
  Difficulty: easy
  motd: "Welcome to Minecraft on a Raspberry Pi cluster!"
  maxWorldSize: 5000
  viewDistance: 6